services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3456:3000
    env_file: /home/sdresen/docker/homepage/.env # use .env
    volumes:
      - /home/sdresen/docker/homepage/config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations, see alternative methods
    environment:
      PUID: $PUID # read them from .env
      PGID: $PGID # read them from .env
    deploy:
      mode: global
      restart_policy:
        condition: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.entrypoints=websecure"
      - "traefik.http.routers.homepage.rule=Host(`homepage.lan.dresen.tech`)"
      - "traefik.http.routers.homepage.tls=true"
      - "traefik.http.routers.homepage.tls.certresolver=production"
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - docker_net
networks:
    docker_net:
      external: true
